### ISSUE TITLE
SelectLongestReads how many reads

### ISSUE THREAD

**Issue by mictadlo** [yechengxi/AssemblyUtility#2]
Hi,
Part of dbg2olc is SelectLongestReads which select reads that sum to total_length of bases.

How many bases do I need for a 1.8G allotetraploid to remain?

Thank you in advance,

MIchal

**Comment by yechengxi** [comment]
That depends on how much coverage data you want to use. Personally I would suggest 20x-30x.

**Comment by olechnwin** [comment]
Just a clarifying question. So, if I want 30x coverage, do I put in 3.2G x 20=64000000000 for total_length for human genome?

**Comment by mictadlo** [comment]
Did you mean `3.2G x 20` or `3.2G x 30`?

**Comment by yechengxi** [comment]
That is the correct way to get total_length though.

**Comment by olechnwin** [comment]
@yechengxi thank you so much for your quick response. 
@mictadlo, I meant 3.2G x 20

**Comment by olechnwin** [comment]
Sorry another question. Since this step is an optional step, can you please explain in what situation I should or should not run this to select reads. Thanks!

**Comment by yechengxi** [comment]
If you have low/moderate coverage and do not need to select the longest reads.

**Comment by olechnwin** [comment]
That means if I have enough coverage, I should select longest reads?

**Comment by yechengxi** [comment]
In practice selecting the longest reads for assembly can lead to better results.

**Comment by mictadlo** [comment]
Hi, 
We have an allotetraploid plant 3.2 G genome and  I ran `fastp --correction -i in.R1.fq.gz -I in.R2.fq.gz -o out.R1.fq.gz -O out.R2.fq.gz`.  As results I got:

```
fastp> zcat OZBenth5_R1.fastp.fq.gz | awk '{if(NR%4==2) print length($1)}' | sort -n | uniq -c
   8555 34
   8175 35
   8216 36
   7711 37
   7591 38
   7533 39
   7335 40
   6967 41
   6839 42
   6695 43
   6241 44
   6363 45
   6241 46
   5988 47
   5869 48
   5574 49
   5374 50
   5312 51
   5211 52
   5401 53
   5291 54
   5255 55
   5133 56
   4862 57
   4810 58
   4706 59
   4393 60
   4352 61
   4008 62
   3923 63
   3613 64
   3543 65
   3355 66
   3161 67
   3083 68
   2719 69
   2568 70
   2418 71
   2279 72
   2202 73
   2134 74
   1889 75
   1756 76
   1779 77
   1718 78
   1700 79
   1652 80
   1476 81
   1439 82
   1409 83
   1441 84
   1390 85
   1407 86
   1502 87
   1414 88
   1486 89
   1462 90
   1434 91
   1470 92
   1546 93
   1602 94
   1492 95
   1630 96
   1669 97
   1761 98
   1814 99
104247667 100
```
I have 6 more libraries. Should I combine all of 7 libraries together?
What would be the best settings for SelectLongestReads for the Illumina reads?
We also have 30x PacBio. What would be the best settings for SelectLongestReads for the Pacbio reads?

Thank you in advance,

Michal
